version: '3.1'

services:
  psqldb:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: user-api
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - "11231:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
